---
- name: Configure nginx web server
  hosts: webserver
  become: True
  tasks:
  - name: Update apt repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: install nginx server
    apt:
      name: nginx
      state: absent
  - name: start nginx server
    service:
      name: nginx
      state: stopped